import { createElement } from 'react';
import ItemDetailScreen from '../../app/item/[id]';
import { ActionButton } from './ActionButton';
import { itemService } from '@/features/items/item.service';
import { reminderService } from '@/features/reminders/reminder.service';
import { useUpdateItem, useArchiveItem, useDeleteItem, useLocationHistory, useMoveItem } from '@/hooks/useItems';
jest.mock('@/features/items/item.service', () => ({ itemService: { getItem: jest.fn() } }));
jest.mock('@/features/reminders/reminder.service', () => ({ reminderService: { getForItem: jest.fn() } }));
jest.mock('@/hooks/useItems', () => ({ useUpdateItem: jest.fn(), useArchiveItem: jest.fn(), useDeleteItem: jest.fn(), useLocationHistory: jest.fn(), useMoveItem: jest.fn() }));
jest.mock('./ItemFields', () => ({ ItemFields: 'MockFields', emptyItemDraft: {} }));
jest.mock('./LocationPicker', () => ({ LocationPicker: (props: any) => require('react').createElement('MockPicker', props, props.renderTrigger(() => props.onVisibleChange(true))) }));
jest.mock('expo-router', () => ({ useLocalSearchParams: () => ({ id: 'charger' }), useFocusEffect: (callback: () => void) => require('react').useEffect(callback, [callback]), Link: 'MockLink', router: { canGoBack: () => true, back: jest.fn(), push: jest.fn(), replace: jest.fn() } }));
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: 'MockSafeArea' }));
jest.mock('react-native', () => {
  const mock = Object.create(jest.requireActual('react-native'));
  for (const name of ['View', 'Text', 'Pressable', 'ScrollView', 'Image', 'ActivityIndicator']) Object.defineProperty(mock, name, { value: 'Mock' + name });
  Object.defineProperty(mock, 'Alert', { value: { alert: jest.fn() } });
  return mock;
});
const { act, create } = require('react-test-renderer');

test('details show real metadata and keep Move, Edit, Save, and photo fallback working', async () => {
  const moveItem = jest.fn().mockResolvedValue({ success: true });
  const updateItem = jest.fn().mockResolvedValue({ success: true });
  const refresh = jest.fn().mockResolvedValue(undefined);
  jest.mocked(useUpdateItem).mockReturnValue({ updateItem, isSubmitting: false, fieldErrors: undefined });
  jest.mocked(useArchiveItem).mockReturnValue({ archiveItem: jest.fn(), isArchiving: false });
  jest.mocked(useDeleteItem).mockReturnValue({ deleteItem: jest.fn(), isDeleting: false });
  jest.mocked(useMoveItem).mockReturnValue({ moveItem, isMoving: false });
  jest.mocked(useLocationHistory).mockReturnValue({ history: [], error: null, isLoading: false, refresh });
  jest.mocked(itemService.getItem).mockResolvedValue({ id: 'charger', name: 'Laptop Charger', photoUri: 'file:///charger.jpg', quantity: 1, unit: 'pc', condition: 'Good', notes: 'Keep in drawer', categoryName: 'Electronics', currentLocationId: 'bedroom', currentLocationPath: 'Bedroom/Cabinet/Drawer 2', createdAt: '2026-08-15T00:00:00Z', tags: [{ id: 'laptop', name: 'Laptop' }], tagIds: ['laptop'] } as any);
  jest.mocked(reminderService.getForItem).mockResolvedValue([]);
  let tree: any;
  await act(async () => { tree = create(createElement(ItemDetailScreen)); });
  const text = () => tree.root.findAllByType('MockText').map((node: any) => node.children.filter((child: any) => typeof child === 'string' || typeof child === 'number').join('')).join('|');
  for (const value of ['Laptop Charger', 'Electronics', 'Laptop', 'Bedroom › Cabinet › Drawer 2', 'Good', 'None', 'Keep in drawer']) expect(text()).toContain(value);
  await act(async () => tree.root.findByType('MockImage').props.onError());
  expect(text()).toContain('No photo');
  const button = (label: string) => tree.root.findAllByType(ActionButton).find((node: any) => node.props.children === label);
  await act(async () => button('⌖ Move').props.onPress());
  expect(tree.root.findByType('MockPicker').props.visible).toBe(true);
  await act(async () => tree.root.findByType('MockPicker').props.onChange('desk'));
  expect(moveItem).toHaveBeenCalledWith('charger', 'desk');
  expect(refresh).toHaveBeenCalledTimes(1);
  await act(async () => button('✎ Edit').props.onPress());
  expect(tree.root.findByType('MockFields').props.value.tagIds).toEqual(['laptop']);
  await act(async () => button('Save Item').props.onPress());
  expect(updateItem).toHaveBeenCalledWith('charger', expect.objectContaining({ quantity: 1, tagIds: ['laptop'] }));
  expect(tree.root.findAllByType('MockFields')).toHaveLength(0);
  await act(async () => tree.unmount());
});
